### ISSUE TITLE
Build fails on CentOS 7 x64

### ISSUE THREAD

**Issue by BearOve** [gchp/termbox-sys#21]
On CentOS x64 waf uses lib64 instead of lib as the output directory. This makes build.rs work, but linking fails with missing static lib for termbox.

I made it work locally by adding a second line with the lib64 directory. However it seems like there should be a more correct way such as setting LIBDIR before calling waf.

**Comment by sherrman** [comment]
I have the same issue on Ubuntu 18.04 x64

**Comment by uggla** [comment]
Same on Fedora.
As explained above making a link lib64 --> lib fixed the issue.

**Comment by gchp** [comment]
Just released 0.2.12 - please let me know if you continue to encounter issues. Thanks!
